spring:
  application:
    name: service7
server:
  port: 8070
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      serviceName: service7
      version: v2.0.0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${MCLUSTER_IP}:${MCLUSTER_PORT}/eureka
